# Generated by Django 2.2.3 on 2019-08-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_group_users'),
        ('matches', '0001_initial'),
        ('profile_and_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerating',
            name='performance_player_rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_player_rated', to='profile_and_stats.UserProfileData'),
        ),
        migrations.AddField(
            model_name='performancerating',
            name='performance_rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_and_stats.UserProfileData'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='associated_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_group', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='profile_and_stats.UserProfileData'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='linked_players', to='profile_and_stats.UserProfileData'),
        ),
        migrations.AddField(
            model_name='availabilitytable',
            name='availability_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_availability_group', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='availabilitytable',
            name='matchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matches.MatchData'),
        ),
        migrations.AddField(
            model_name='availabilitytable',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_detail', to='profile_and_stats.UserProfileData'),
        ),
    ]
