# Generated by Django 2.2.3 on 2019-08-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_and_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subscription_length_in_days', models.DecimalField(decimal_places=0, max_digits=3)),
                ('subscribed_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile_and_stats.UserProfileData')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_donation', models.DateField(auto_now_add=True)),
                ('donation_amount_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('donated_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profile_and_stats.UserProfileData')),
            ],
        ),
    ]
