# Generated by Django 2.2.3 on 2019-08-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_and_stats', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='my_group', to='profile_and_stats.UserProfileData'),
        ),
    ]
